on:
  schedule:
    - cron:  '0 5 * * *'
  workflow_dispatch:  # click the button on Github repo!

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync master with upstream latest

    steps:
    # Step 1: run a standard checkout action, provided by GitHub
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref: master

    # Step 2: run sync action
    - name: Pull upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v2.1
      with:
        upstream_repository: getstencil/GoogleWebFonts-FontFamilyPreviewImages
        upstream_branch: master
        target_branch: master
        git_pull_args: --ff-only

    # Step 3: Display a message if 'sync' step had new commits
    - name: Check for new commits
      if: steps.sync.outputs.has_new_commits
      run: echo "Fonts were updated."

    # Step 4: Print timestamp for records
    - name: Timestamp
      run: date